### ISSUE TITLE
Hey, I'd love to see this on our addon gallary.

### ISSUE THREAD

**Issue by arunoda** [philcockfield/storybook-host#1]
This is the [file](https://github.com/kadirahq/getstorybook.io/blob/master/src/docs/react-storybook/addons/addon-gallery.js) you need to add this.

**Comment by philcockfield** [comment]
Hey @arunoda - that's pointing to a broken link.

**Comment by arunoda** [comment]
Oh! sorry for that.
We did a new PR yesterday.
Check the link now. I corrected it.

**Comment by philcockfield** [comment]
https://getstorybook.io/docs/react-storybook/addons/addon-gallery

![image](https://cloud.githubusercontent.com/assets/185555/20041140/e7dc3b04-a4c9-11e6-80db-892eb1d1838a.png)
