### ISSUE TITLE
normalize has precedence over custom css

### ISSUE THREAD

**Issue by jdevega** [philcockfield/storybook-host#14]
I have added a css file in my head.html file to load my app styles, but as normalize.css is being added into head > styles before my css, its rules take precedence over mine ones.
For example, I have an h1 with no margin in my css, but normalize set its margin to "margin: 0.67em 0;" ( normalize.css:51 )

**Comment by damusnet** [comment]
Same here.

Sadly this renders `storybook-host` unusable as it overrides any css loaded globally beforehand.

**Comment by brentmclark** [comment]
Yep.  Can this line be completely removed from the code @philcockfield?

https://github.com/philcockfield/storybook-host/blob/master/src/index.ts#L1

I am not entirely sure why you would even need a normalize.css, but if you can shed some light on that I would be happy to work on a PR to implement the styles you'll need to support this tool. 

Until then, this addon will remain unusable to me as well.

**Comment by robertpiira** [comment]
For now I'm using 'null-loader' to exclude normalize.css in webpack settings. Temp fix for this issue.

**Comment by Josh-a-e** [comment]
@robertpiira I found that adding this to my jest config was slightly preferable to tinkering with webpack config (with the jest config being testing specific):

```
"moduleNameMapper": {
    "\\.(css|less)$": "identity-obj-proxy"
},
```

**Comment by klaaz0r** [comment]
I don't think normalize should be inside host, it should be the responsible of the developer  

adding to @robertpiira 's comment: 

```javascript
const path = require('path')

module.exports = {
  module: {
    rules: [
      {
        test: /\.scss$/,
        loaders: ['style-loader', 'css-loader', 'sass-loader']
      },
      {
        // don't use normalize from storybook host
        test: path.resolve(__dirname, '../node_modules/storybook-host/assets/css/normalize.css'),
        use: 'null-loader'
      }
    ]
  }
}
```

**Comment by philcockfield** [comment]
Hey chaps!  Please see version `5.0.0` which has the `normalize.css` dependency removed. (pr #35).
