### ISSUE TITLE
es6 target for TypeScript breaks build-storybook during uglify step

### ISSUE THREAD

**Issue by trabianmatt** [philcockfield/storybook-host#24]
The TypeScript compilation output in `/lib` includes es6 syntax such as arrow functions. This is preventing us from being able to build a static version of the storybook (via `build-storybook`) because the uglify step is failing. Would it be possible to have es5 as the output target?

**Comment by philcockfield** [comment]
Good call @trabianmatt - sure can.

**Comment by philcockfield** [comment]
Published no NPM as `4.1.1`.  Let me know if that's working of you @trabianmatt.  
I thought I'd done this ages ago! :)

**Comment by trabianmatt** [comment]
Worked great - thanks!!
