### ISSUE TITLE
Release new version compatible with React 17

### ISSUE THREAD

**Issue by alexandernst** [philcockfield/storybook-host#57]
React 17 was just released. There are no breaking changes, but if I try to use it with this package, I get warnings about missing peer-dependencies (this package depends on react@16.x).

Can you release a new version making this package compatible with React 17? @philcockfield

**Comment by alexandernst** [comment]
I'll gladly create a MR if you're willing to merge it and release a new version :)

**Comment by philcockfield** [comment]
Done, released on NPM as `v5.2.0`
Thanks @alexandernst
